pipeline {
    agent any

    triggers {
        // Step 2: GitHub webhook trigger
        githubPush()
    }

    stages {

        stage('Checkout Code') {
            steps {
                // Step 4: Pull latest code
                git branch: 'main', url: 'https://github.com/AryanKoshal10/Student-Feedback-Form-Selenium.git'
            }
        }

        stage('Build Setup') {
            steps {
                // Step 5 & 6: Install dependencies
                dir('Student-Feedback-Form') {
                    bat 'echo Installing dependencies...'
                    bat 'pip install selenium'
                }
            }
        }

        stage('Run Tests') {
            steps {
                // Step 7: Execute selenium_test.py
                dir('Student-Feedback-Form') {
                    bat 'echo Running Selenium Tests...'
                    bat 'python selenium_test.py'
                }
            }
        }
    }

    post {
        success {
            // Step 8 & 9: Feedback
            echo 'Build Successful - All tests passed'
        }
        failure {
            echo 'Build Failed - Check test cases'
        }
    }
}
