pipeline {
    agent any

    stages {

        stage('Clone Repo') {
            steps {
                git branch: 'main', url: 'https://github.com/AryanKoshal10/Student-Feedback-Form-Selenium.git'
            }
        }

        stage('Run Selenium Test') {
            steps {
                bat 'cd Student-Feedback-Form && pip install selenium'
                bat 'cd Student-Feedback-Form && python selenium_test.py'
            }
        }
    }

    post {
        success {
            echo 'Build Successful'
        }
        failure {
            echo 'Build Failed'
        }
    }
}
